### ISSUE TITLE
Arrumar a build para rodar o backend corretamente

### ISSUE THREAD

**Issue by Gxaite** [unb-mds/2024-1-MinasDeCultura#101]
## **Descrição**
A build do Docker para o backend não está funcionando conforme o esperado. Isso está impedindo a correta execução do backend na infraestrutura Docker. Precisamos identificar e corrigir os problemas na configuração atual para garantir que o backend seja compilado e executado corretamente em contêineres Docker.

## **Tarefas**
- [x] **Analisar o arquivo Dockerfile**: Revisar o Dockerfile atual para identificar possíveis problemas de configuração.
- [x] **Verificar dependências**: Assegurar que todas as dependências necessárias para o backend estão sendo corretamente instaladas durante a build.
- [x] **Testar a build localmente**: Executar a build localmente para identificar erros e ajustar as configurações conforme necessário.
- [x] **Atualizar o Docker Compose**: Se necessário, fazer ajustes no arquivo `docker-compose-local.yml` para garantir a compatibilidade com as mudanças realizadas no Dockerfile.
- [x] **Documentar mudanças**: Atualizar a documentação do projeto com as mudanças feitas para que os outros membros da equipe estejam cientes.
- [x] **Testar a nova build no ambiente de desenvolvimento**: Após realizar as correções, testar a build no ambiente de desenvolvimento para garantir que o backend está funcionando corretamente.

**Comment by WillxBernardo** [comment]
Foi alterado a build do docker file para conter o node, removendo a build antiga onde eram instaladas as bibliotecas para os raspadores em python.
