### ISSUE TITLE
Adicionar Balão de Destaque ao Componente de Busca Filtrada

### ISSUE THREAD

**Issue by Gxaite** [unb-mds/2024-1-MinasDeCultura#102]
## **Descrição**
O componente de busca filtrada no site precisa de um destaque visual adicional para melhorar a experiência do usuário. Será adicionado um balão de destaque ao redor do campo de busca, que deve chamar a atenção do usuário para essa funcionalidade importante.

## **Tarefas**
- [x] **Projetar o balão de destaque**: Criar o design do balão, definindo as cores, bordas e qualquer animação que possa ser usada para destacar o componente.
- [x] **Implementar o balão no frontend**: Adicionar o balão de destaque ao componente de busca filtrada no código do frontend.
- [x] **Testar a nova funcionalidade**: Verificar se o balão está aparecendo corretamente em diferentes navegadores e tamanhos de tela.
- [x] **Obter feedback da equipe**: Compartilhar a implementação com a equipe para receber feedback e fazer ajustes, se necessário.
- [x] **Documentar a mudança**: Atualizar a documentação do projeto com detalhes sobre o novo balão de destaque, incluindo capturas de tela e explicações de estilo.

**Comment by Mateushqms** [comment]
O destaque na pesquisa foi adicionado, e não foi apresentado nenhum problema.
![image](https://github.com/user-attachments/assets/187ef33e-039c-4bf3-bf09-7f7197fa54f0)
