### ISSUE TITLE
Integrar o Backend em Node.js com os Scripts de Raspagem em Python

### ISSUE THREAD

**Issue by Gxaite** [unb-mds/2024-1-MinasDeCultura#103]
## **Descrição**
Precisamos integrar o backend desenvolvido em Node.js com os scripts de raspagem escritos em Python. Essa integração permitirá que o backend acione os scripts de raspagem conforme necessário, processando os dados raspados e disponibilizando-os através das APIs. A comunicação entre Node.js e Python deve ser eficiente e robusta para garantir a confiabilidade do sistema.

## **Tarefas**
- [x] **Definir a interface de comunicação**: Decidir como o backend em Node.js irá chamar e se comunicar com os scripts Python (ex.: via chamada de sistema, HTTP, ou usando uma biblioteca como `child_process`).
- [x] **Implementar chamadas do backend**: Escrever as funções no backend Node.js para acionar os scripts Python e capturar suas saídas.
- [x] **Tratar erros e exceções**: Garantir que erros nos scripts Python sejam corretamente capturados e tratados no backend, evitando falhas no sistema.
- [x] **Testar a integração localmente**: Validar a integração em um ambiente local, simulando as condições reais de operação.
- [x] **Documentar a integração**: Atualizar a documentação do projeto para explicar como o backend e os scripts Python estão integrados, incluindo instruções de configuração e uso.

**Comment by isaacbatista26** [comment]
A integração entre o backend e os raspadores foi feita com sucesso. O script que insere os dados no banco de dados é ativado mensalmente, fazendo com o que os dados sempre sejam atualizados. Issue fechada!
