### ISSUE TITLE
Adicionar Seção "Quem Somos Nós" na Página Sobre

### ISSUE THREAD

**Issue by Gxaite** [unb-mds/2024-1-MinasDeCultura#107]
## **Descrição**
Precisamos melhorar a página "Sobre" do projeto adicionando uma nova seção "Quem Somos Nós". Essa seção deve conter uma pequena descrição de cada membro da equipe, incluindo suas fotos, links para seus perfis no LinkedIn e GitHub, para tornar a página mais informativa e pessoal.

## **Tarefas**
- [x] **Criar a estrutura da seção**: Desenvolver a estrutura HTML e CSS para a nova seção "Quem Somos Nós" na página Sobre.
- [x] **Coletar informações dos membros**: Reunir as descrições, fotos, e links de LinkedIn e GitHub de todos os membros da equipe.
- [x] **Adicionar fotos dos membros**: Incluir as fotos dos membros na nova seção, garantindo que estejam bem dimensionadas e otimizadas para web.
- [x] **Adicionar descrições e links**: Inserir as pequenas descrições e os links de LinkedIn e GitHub de cada membro abaixo de suas respectivas fotos.
- [x] **Testar o layout**: Verificar o layout e a responsividade da nova seção em diferentes dispositivos e navegadores para garantir que a apresentação esteja correta.
- [x] **Obter feedback da equipe**: Compartilhar a nova seção com a equipe para revisões e possíveis ajustes.
- [x] **Documentar as alterações**: Atualizar a documentação do projeto com detalhes sobre a nova seção "Quem Somos Nós", incluindo instruções para futuras atualizações de informações dos membros.

**Comment by Mateushqms** [comment]
Foi criado a seção "Quem Somos nós", foi criada como um componente que já possui os testes feitos e um layout responsivo. Possuindo também a imagem e os links do Github e Linkedin dos integrantes.

![image](https://github.com/user-attachments/assets/848887fd-ffd4-4752-910c-497ffff4b7fb)
