### ISSUE TITLE
# Correção do Frontend para Conformidade com o Padrão do Lint

### ISSUE THREAD

**Issue by Gxaite** [unb-mds/2024-1-MinasDeCultura#116]
## Descrição
O frontend do projeto atualmente não está em conformidade com o padrão do lint configurado. Esta issue tem como objetivo revisar e corrigir o código frontend para garantir que ele passe sem erros ou avisos no processo de linting. Isso ajudará a manter a qualidade do código e evitar problemas futuros relacionados a estilo e consistência.

## Tarefas
- [x] Revisar o código frontend atual e identificar as áreas que não estão em conformidade com o padrão do lint.
- [x] Corrigir os erros e avisos identificados pelo lint, ajustando o código conforme necessário.
- [x] Executar o lint novamente para garantir que todas as correções foram bem-sucedidas e que o código agora está em conformidade.
- [x] Realizar testes para garantir que as correções do lint não introduziram novos problemas ou afetaram a funcionalidade existente.
- [x] Atualizar a documentação (se necessário) para refletir as mudanças feitas no código.

**Comment by devMarcosVM** [comment]
Os erros do lint foram completamente resolvidos. O código frontend agora está em conformidade com o padrão do lint, sem erros ou avisos. Isso garante a manutenção da qualidade do código e evita problemas futuros relacionados a estilo e consistência.
