### ISSUE TITLE
Criação da landingpage do projeto

### ISSUE THREAD

**Issue by WillxBernardo** [unb-mds/2024-1-MinasDeCultura#136]
## Descrição
Para melhor documentação sobre o produto Minas de Cultura mostra-se necessário a criação de uma landingpage no qual deve buscar explicar sobre o produto Minas de Cultura.

## Tarefas

- [x] Criação da landingpage
- [x] Contendo conteúdo explicando sobre o objetivo do projeto, como utilizar e opções para acessar a documentação e repositório do projeto

**Comment by Gxaite** [comment]
A landing page do proejto foi criada e testada, ela foi aprovada pelo intgrantes em questão de design, alguns retoques podem ser nesessários, mas a base já está feita
