### ISSUE TITLE
Estudo de Next (react e node)

### ISSUE THREAD

**Issue by Gxaite** [unb-mds/2024-1-MinasDeCultura#45]
### Descrição
Realizar um estudo aprofundado sobre o framework Next.js, incluindo sua integração com React e Node.js. O objetivo é compreender suas funcionalidades, melhores práticas e como utilizá-lo de maneira eficaz em nossos projetos.

### Tarefas
- [x] **Introdução ao Next.js**
  - [x] Ler a documentação oficial do Next.js
  - [x] Assistir a tutoriais introdutórios sobre Next.js
  - [x] Instalar e configurar um projeto básico de Next.js

- [x] **Fundamentos de React no Next.js**
  - [x] Revisar os conceitos fundamentais do React utilizados no Next.js
  - [x] Implementar componentes React em um projeto Next.js
  - [x] Estudar a integração de hooks do React com Next.js

**Comment by isaacbatista26** [comment]
A equipe concluiu com sucesso o estudo aprofundado sobre o framework Next.js, incluindo sua integração com React e Node.js. As seguintes tarefas foram realizadas:

**Introdução ao Next.js:**
- Lemos a documentação oficial do Next.js.
- Assistimos a tutoriais introdutórios sobre Next.js.
- Instalamos e configuramos um projeto básico de Next.js.

**Fundamentos de React no Next.js:**
- Revisamos os conceitos fundamentais do React utilizados no Next.js.
- Implementamos componentes React em um projeto Next.js.
- Estudamos a integração de hooks do React com Next.js.

Com este conhecimento, estamos agora bem preparados para utilizar Next.js de maneira eficaz em nossos projetos. Se houver necessidade de revisitar algum tópico ou aprofundar mais em qualquer área específica, estamos prontos para isso.
