### ISSUE TITLE
Prototipação inicial do figma

### ISSUE THREAD

**Issue by Gxaite** [unb-mds/2024-1-MinasDeCultura#50]
### Descrição
Criar uma prototipação inicial no Figma, incluindo a definição de cores, fontes e outros elementos básicos de design.

### Tarefas

- [x] Definir a paleta de cores principal e secundária
- [x] Selecionar as fontes para títulos e texto
- [x] Criar um estilo de botão padrão
- [x] Desenvolver um layout básico para uma página inicial
- [x] Documentar as decisões de design e compartilhar o protótipo com a equipe

**Comment by manuvaladares** [comment]
![home (2)](https://github.com/user-attachments/assets/32b6dbe4-2d61-4ea7-b665-fdba88ab9e48)
