### ISSUE TITLE
Desenvolvimento da Responsividade do Frontend e Criação de Menu de Navegação Responsivo

### ISSUE THREAD

**Issue by Mateushqms** [unb-mds/2024-1-MinasDeCultura#63]
### Descrição
Desenvolver a responsividade das páginas Home e Sobre, criar um menu de navegação responsivo na Header e ajustar o layout do Footer. Verificar se todos os botões da página, assim como o logo na Header, estão redirecionando corretamente.

### Tarefas
- [x] Implementar responsividade para todas as telas na página Sobre
- [x] Implementar responsividade para todas as telas na página Home
- [x] Criar um menu de navegação responsivo na Header
- [x] Verificar e corrigir redirecionamento em todos os botões das páginas
- [x] Ajustar o Footer para ser responsivo

**Comment by devMarcosVM** [comment]
Todas as tarefas relacionadas à responsividade e ajustes no layout das páginas Home e Sobre foram concluídas. Implementamos a responsividade para todas as telas em ambas as páginas, criando um menu de navegação responsivo na Header que se adapta ao tamanho da tela, garantindo uma experiência de usuário fluida em dispositivos móveis e desktops. Todos os botões foram revisados para assegurar que os redirecionamentos funcionem corretamente, incluindo o logo na Header que agora direciona para a página inicial como esperado. O Footer também foi ajustado para ser totalmente responsivo. 

## PC
[Gravação de tela de 29-07-2024 11:43:12.webm](https://github.com/user-attachments/assets/5f975590-54f5-4f26-a07d-a833e0cd7b15)

## MOBILE
[Gravação de tela de 29-07-2024 11:44:17.webm](https://github.com/user-attachments/assets/0a1d6c62-e073-4964-a133-894ad53c9bf6)
