### ISSUE TITLE
Coleta de dados de juiz de fora utilizando scrapy

### ISSUE THREAD

**Issue by Gxaite** [unb-mds/2024-1-MinasDeCultura#64]
## Descrição
Estamos utilizando o Scrapy para coletar dados relacionados a eventos culturais, artistas locais e locais de eventos em Juiz de Fora. O objetivo é criar um banco de dados centralizado para facilitar a divulgação e o acesso às informações culturais da cidade. Precisamos garantir que a coleta de dados seja precisa, atualizada e organizada de maneira estruturada.

## Tarefas
- [x] Configurar o projeto Scrapy para o site alvo, incluindo a criação de um novo spider.
- [x] Estruturar e salvar os dados coletados em um formato de banco de dados apropriado JSON.
- [x] Implementar validações e verificações para garantir a qualidade e a atualização dos dados coletados.
- [x] Documentar o processo de raspagem, incluindo os desafios encontrados e as soluções implementadas.

**Comment by manuvaladares** [comment]
A raspagem do site de Juiz de Fora foi concluída com sucesso. Durante o processo, tivemos insights e descobertas valiosas sobre os problemas que enfrentávamos anteriormente.

Identificamos que a nossa aranha não conseguia acessar o site porque ele bloqueava bots. Para resolver esse problema, criamos um header personalizado que permitiu a entrada sem ser bloqueado pelo servidor. Com essa solução, conseguimos acessar o site e gerar o arquivo JSON necessário.

![image](https://github.com/user-attachments/assets/6c4d9814-a89d-424a-81f0-4eaf6fe72b9a)

Trecho de código que configura o acesso:

```python
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, Gecko) Chrome/91.0.4472.124 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5',
    'Accept-Encoding': 'gzip, deflate, br',
    'Connection': 'keep-alive',
    'Upgrade-Insecure-Requests': '1',
    'TE': 'Trailers',
}
