### ISSUE TITLE
Criar o raspador de montes claros usando selenium

### ISSUE THREAD

**Issue by Gxaite** [unb-mds/2024-1-MinasDeCultura#65]
## Descrição
Desenvolver um raspador web para coletar dados de gastos públicos voltados à cultura no município de Montes Claros. O raspador deve utilizar a biblioteca Selenium para automatizar a navegação e extração de dados das páginas web específicas. Este raspador faz parte da iniciativa de criar um site para consultar os gastos públicos no estado de Minas Gerais, permitindo que os cidadãos tenham acesso transparente a essas informações.

## Tarefas
- [x] Analisar a estrutura das páginas web de Montes Claros para identificar os elementos HTML necessários para a extração de dados.
- [x] Configurar o ambiente de desenvolvimento com Selenium e outras dependências necessárias.
- [x] Criar o script inicial de Selenium para acessar e navegar pelas páginas de interesse.
- [x] Implementar a lógica de extração de dados, capturando as informações relevantes sobre os gastos públicos.
- [x] Testar o raspador para garantir que os dados sejam extraídos corretamente e tratar possíveis erros de navegação ou extração.
- [x] Documentar o código e o processo de execução do raspador para futuras manutenções e atualizações.

**Comment by manuvaladares** [comment]
A tarefa foi concluida com sucesso e a raspagem do site de Montes Claros está sendo feita. O script retorna csv's na pasta 'downloads', os quais vão ser tratados para entrar no banco de dados. O código consegue executar o Selenium através de um WebDriver, o qual entra no site de Montes Claros e busca, mês por mês, as despesas gerais do governo municipal.


![image](https://github.com/user-attachments/assets/cac96d39-a210-48a7-8455-c00c41813f24)
