### ISSUE TITLE
Testes unitários backend

### ISSUE THREAD

**Issue by Gxaite** [unb-mds/2024-1-MinasDeCultura#70]
## Descrição
Desenvolver e implementar testes para o backend para garantir a qualidade e a robustez do código, abordando áreas críticas sem cobertura adequada.

## Tarefas
- [x] **Análise do Código**
  - Identificar áreas críticas e documentar módulos/funções chave.
  
- [x] **Configuração do Ambiente**
  - Configurar dependências e frameworks de teste (ex.: Jest, Mocha).
  
- [x] **Testes Unitários**
  - Criar testes para funções/módulos isolados, cobrindo casos de sucesso e falhas.

- [x] **Revisão e Otimização**
  - Revisar a eficiência e a cobertura dos testes, otimizando quando necessário.

- [x] **Documentação**
  - Documentar execução de testes e instruções para a equipe.

**Comment by isaacbatista26** [comment]
Os testes foram feitos com sucesso. Neles, testamos os três endpoints da nossa API (`/tenders`, `/cities`, `/units`) e a conexão com o banco de dados. Os testes confirmaram que:

- O endpoint `/tenders` retorna corretamente as licitações dentro do intervalo de datas e para a cidade especificada.
- O endpoint `/cities` retorna corretamente a lista de cidades disponíveis.
- O endpoint `/units` retorna corretamente a lista de unidades administrativas.

Além disso, o teste de conexão com o Supabase garantiu que as variáveis de ambiente são carregadas corretamente e que o cliente do Supabase está configurado e funcionando como esperado.

Todos os testes passaram sem erros e confirmaram que as funcionalidades estão operacionais. A issue pode ser fechada.
