### ISSUE TITLE
Testes unitários e de componentes

### ISSUE THREAD

**Issue by Gxaite** [unb-mds/2024-1-MinasDeCultura#71]
## Descrição
Desenvolver e implementar uma variedade de testes para o frontend, incluindo testes unitários, de integração e de interface de usuário, para assegurar a qualidade e a estabilidade da aplicação.

## Tarefas
- [x] **Análise do Código**
  - Identificar componentes críticos e fluxos de usuário que necessitam de testes.
  
- [x] **Configuração do Ambiente de Testes**
  - Configurar frameworks e ferramentas de teste (ex.: Jest, React Testing Library, Cypress).

- [x] **Testes Unitários**
  - Desenvolver testes para componentes individuais, verificando renderização correta e comportamento esperado.

- [x] **Documentação**
  - Documentar os procedimentos de execução dos testes e as melhores práticas para manutenção contínua.

**Comment by devMarcosVM** [comment]
Tivemos problemas na configuração do ambiente de trabalho, o que nos causou um atraso significativo. Inicialmente, testamos usar o Vitest, mas acabamos optando por manter o Jest e o React Testing Library como nossas ferramentas principais de testes. Após resolver a configuração preliminar do ambiente, conseguimos realizar os primeiros testes nos componentes. 

Foi criada a documentação de como executar os testes no front-end, garantindo que o processo seja claro e acessível para todos os membros da equipe. A documentação inclui desde a clonagem do repositório até a execução dos testes, além de orientações sobre como lidar com mensagens de erro e a importância de manter os testes atualizados à medida que o projeto evolui. Isso facilita a compreensão e execução dos testes, assegurando que o código permaneça otimizado e funcional.
