### ISSUE TITLE
Tratar e filtrar csv gerado pelo Selenium 

### ISSUE THREAD

**Issue by manuvaladares** [unb-mds/2024-1-MinasDeCultura#74]
## Descrição
Precisamos concluir o desenvolvimento do script do raspador para garantir que ele extraia corretamente os dados dos últimos dois anos a partir do site de transparência. Além disso, é necessário criar um script adicional para tratar e filtrar os dados do CSV gerado, para que possamos analisar as informações de maneira eficaz.

## Tarefas
- [x] Certificar-se de que o script clique corretamente nos elementos da página para gerar e baixar o CSV.
- [x] Montar o loop para pegar dos ultimos 2 anos.
- [x] Tratar o csv e devolver um json

**Comment by Gxaite** [comment]
Issue resolvida com sucesso. O script foi ajustado para lidar adequadamente com meses futuros sem dados, adicionando entradas "nulas" ao JSON conforme necessário. Além disso, todos os arquivos CSV são excluídos automaticamente após o processamento. Testes realizados confirmam que o script está funcionando conforme esperado, tanto para meses com dados quanto para meses sem dados disponíveis. A issue pode ser fechada.
