### ISSUE TITLE
Feedback rapido

### ISSUE THREAD

**Issue by RochaCarla** [unb-mds/2024-1-MinasDeCultura#81]
Pessoal, 
as contrições de vcs está baixa. É esperado que a produtividade aumente na R2 e a de vcs diminuiu. Além disso, tem 3 semanas que não atualizam a documentação e desde maio não tem contribuição efetiva no repositório. A disciplina é de aplicação de métodos ágeis. Se organizem para melhorar a produtividade e a entrega individual/coletivo

**Comment by Gxaite** [comment]
Obrigado pelo feedback professora, desde sua primeira mensagem estamos atentos a isso. Estavamos segurando vários commits na branch developer pra não subir modificações quebradas para a main. Vamos criar ciclos de Pull Request para a main de forma mais frequente. Estamos trabalhando a todo vapor!
